
path: C:/Users/Enes/Desktop/python/2-Deep Learning/2-Computer Vision/2-Computer Vision-Object Detection/2-YOLO Video object detection/4-plate recognition/data # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: plate